select player as jogador, K as num_abates from `worlds 2021 main event - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2020 main event - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2019 main event - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2018 main event - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2017 main event - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2016 - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2015 - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds 2014 - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds season 1 - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds season 2 - player stats` order by K desc limit 1;
select player as jogador, K as num_abates from `worlds season 3 - player stats` order by K desc limit 1;